### PR TITLE
added mask option to plotting.py

### PR DESCRIPTION
**Pull request by margulies**
Let me know what further changes should be made to fully incorporate the mask if needed...

### CODE REVIEW

**Comment by juhuntenburg** [comment]
Cool,  thanks! Only, is there a reason that the mask can only be applied if the bg_on_stat (terrible name I should change that at some point) is turned on?
Thanks!

**Comment by margulies** [comment]
Good point -- I've now added this option as well. Let me know if any
additional changes should be made.

Thanks!

**Comment by juhuntenburg** [comment]
Looks good, thanks!

**Comment by juhuntenburg** [comment]
I just fixed a small thing that raised and error for me ("if mask"), but still, if I set a mask it just sets everything to the background... do you understand why? Otherwise I'll look at it closer another time, also how to integrate with the threshold and label options.
Thanks!

**Pull request merged**
